### ISSUE TITLE
not reading "remote" from config properly

### ISSUE THREAD

**Issue by wesyoung** [csirtgadgets/py-cgcif#1]
double check this and --no-verify-ssl

**Comment by motok** [comment]
In /usr/local/lib/python2.7/dist-packages/cgcif/__init__.py,

 80     options = {}
 81     if os.path.isfile(args.config):
 82         f = file(args.config)
 83         config = yaml.load(f)
 84         f.close()
 85         if not config:
 86             raise Exception("Unable to read " + args.config + " config file"    )
 87         for k in config:
 88             if not options.get(k):
 89                 options[k] = config[k]


and following lines actually read ~app/.cg.yaml and import the
configuration, but

  105     args = vars(args)
  106     for v in args:
  107         if v == 'cif_remote': continue
  108         if args[v]:
  109             options[v] = args[v]

overwrites options[] with the defaults.

Simply deleting this paragraph or moving to line 79 flashed into my
mind.

**Comment by wesyoung** [comment]
i think e82c403 solves it, but we're to the point where the logic should be re-factored so it's easier to read :x

gonna do some testing before i merge into master..

**Comment by wesyoung** [comment]
fwiw, re-factoring a bit over here:

https://github.com/csirtgadgets/py-cgcif/commit/4cabf67ca306fcaab2ef0b282cf77b88e2f74782

(branch fix/refactor)

**Comment by motok** [comment]
Thanks, but still it doesn't work.

(1)
Since you named 'logging.py' in cg-cif/ directory, "import logging" sentences in files in this directory will 
import cg-cif/logging.py and this is not the logging module provided by python itself.
Hence, you'll see an AttributeError: 'module' object has no attribute 'WARNING'.

ubuntu@dauntless:~$ sudo -s
root@dauntless:~# su - app
app@dauntless:~$ cg-cif --config /home/app/.cg.yml -d 
Traceback (most recent call last):
  File "/usr/local/bin/cg-cif", line 9, in <module>
    load_entry_point('py-cgcif==4cabf67ca306fcaab2ef0b282cf77b88e2f74782', 'console_scripts', 'cg-cif')()
  File "/usr/local/lib/python2.7/dist-packages/py_cgcif-4cabf67ca306fcaab2ef0b282cf77b88e2f74782-py2.7.egg/cgcif/client.py", line 71, in main
    setup_logging(args)
  File "/usr/local/lib/python2.7/dist-packages/py_cgcif-4cabf67ca306fcaab2ef0b282cf77b88e2f74782-py2.7.egg/cgcif/logging.py", line 7, in setup_logging
    loglevel = logging.WARNING
AttributeError: 'module' object has no attribute 'WARNING'
app@dauntless:~$ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 

(2)
renaming logging.py with cgcif_logging.py, I got the error;

app@dauntless:~$ cg-cif --config /home/app/.cg.yml -d 
Traceback (most recent call last):
  File "/usr/local/bin/cg-cif", line 9, in <module>
    load_entry_point('py-cgcif==4cabf67ca306fcaab2ef0b282cf77b88e2f74782', 'console_scripts', 'cg-cif')()
  File "/usr/local/lib/python2.7/dist-packages/py_cgcif-4cabf67ca306fcaab2ef0b282cf77b88e2f74782-py2.7.egg/cgcif/client.py", line 88, in main
    if options.get('risk', RISKS):
AttributeError: 'NoneType' object has no attribute 'get'
app@dauntless:~$ 

It seems because setup_configs() doesn't return any object which has
get() method.


thanks.
